version: "3.8"

services:
    db:
        image: postgres:16
        restart: always
        # set shared memory limit when using docker-compose
        shm_size: 128mb
        # or set shared memory limit when deploy via swarm stack
        #volumes:
        #  - type: tmpfs
        #    target: /dev/shm
        #    tmpfs:
        #      size: 134217728 # 128*2^20 bytes = 128Mb
        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_NAME}
        ports:
            - "5432:5432"
        volumes:
            - D:/Documents/volumes/postgres-next-shadcn/db-data:/var/lib/postgresql/data

    adminer:
        image: adminer
        ports:
            - 8080:8080

    cloudbeaver:
        image: dbeaver/cloudbeaver:24
        container_name: cloudbeaver
        ports:
            - "8088:8978"
        volumes:
            - D:/Documents/volumes/postgres-next-shadcn/workspace:/workspace
